### ISSUE TITLE
Backend infrastructure for login verification 

### ISSUE THREAD

**Issue by nearly-trinity** [CSCI-3321-Software-Engineering/captain-america#2]
Backend logic and api endpoints for login verification, should accept some username and password and output some classification of student, professor, or admin (S, P, A).

** TODO

- [x] Create service function call in iron-man
- [x] create post request for accepting username and password from iron-man
- [x] return boolean with correct username and password
